import { isPlatformBrowser } from '@angular/common';
import { Injectable, PLATFORM_ID, inject, signal } from '@angular/core';

import { AppLanguage, LocalizedText } from '../../shared/models/content';

const storageKey = 'qazaq_language';

const dictionary: Record<string, Record<AppLanguage, string>> = {
  home: { ru: 'Главная', en: 'Home', kz: 'Басты бет' },
  levels: { ru: 'Уровни', en: 'Levels', kz: 'Деңгейлер' },
  leaderboard: { ru: 'Лидерборд', en: 'Leaderboard', kz: 'Көшбасшылар' },
  arcade: { ru: 'Аркада', en: 'Arcade', kz: 'Аркада' },
  profile: { ru: 'Профиль', en: 'Profile', kz: 'Профиль' },
  sign_in: { ru: 'Вход', en: 'Sign in', kz: 'Кіру' },
  register: { ru: 'Регистрация', en: 'Register', kz: 'Тіркелу' },
  log_out: { ru: 'Выход', en: 'Log out', kz: 'Шығу' },
  create_account: { ru: 'Создать аккаунт', en: 'Create account', kz: 'Аккаунт ашу' },
  choose_teacher: { ru: 'Выбрать учителя', en: 'Choose teacher', kz: 'Мұғалім таңдау' },
  request_change: { ru: 'Сменить учителя', en: 'Request teacher change', kz: 'Мұғалімді ауыстыру' },
  feedback: { ru: 'Отзыв и идеи', en: 'Feedback and ideas', kz: 'Пікір және идеялар' },
  daily_tasks: { ru: 'Ежедневные задания', en: 'Daily tasks', kz: 'Күнделікті тапсырмалар' },
  weekly_challenge: { ru: 'Недельный челлендж', en: 'Weekly challenge', kz: 'Апталық челлендж' },
  submit: { ru: 'Отправить', en: 'Submit', kz: 'Жіберу' },
  save: { ru: 'Сохранить', en: 'Save', kz: 'Сақтау' },
  next: { ru: 'Далее', en: 'Next', kz: 'Келесі' },
  finish: { ru: 'Завершить', en: 'Finish', kz: 'Аяқтау' },
  play_audio: { ru: 'Прослушать', en: 'Play audio', kz: 'Тыңдау' },
  record_answer: { ru: 'Записать ответ', en: 'Record answer', kz: 'Жауап жазу' },
  stop_recording: { ru: 'Остановить запись', en: 'Stop recording', kz: 'Жазуды тоқтату' },
  attempts_left: { ru: 'Осталось попыток', en: 'Attempts left', kz: 'Қалған мүмкіндік' },
  plays_left: { ru: 'Осталось прослушиваний', en: 'Plays left', kz: 'Қалған тыңдау саны' },
  teacher_tasks: { ru: 'Задания учителя', en: 'Teacher tasks', kz: 'Мұғалім тапсырмалары' },
  create_task: { ru: 'Создать задание', en: 'Create task', kz: 'Тапсырма құру' },
  mark_complete: { ru: 'Отметить выполненным', en: 'Mark complete', kz: 'Орындалды деп белгілеу' },
  current_teacher: { ru: 'Текущий учитель', en: 'Current teacher', kz: 'Қазіргі мұғалім' },
  no_teacher: { ru: 'Учитель ещё не выбран', en: 'Teacher is not selected yet', kz: 'Мұғалім әлі таңдалмаған' },
  language: { ru: 'Язык', en: 'Language', kz: 'Тіл' },
  brand_subtitle: {
    ru: 'Платформа для языка и культуры',
    en: 'Language and culture platform',
    kz: 'Тіл мен мәдениет платформасы',
  },
  hero_eyebrow: {
    ru: 'Цифровая платформа для развития казахского языка',
    en: 'Digital platform for Kazakh language growth',
    kz: 'Қазақ тілін дамытуға арналған цифрлық платформа',
  },
  hero_title: {
    ru: 'Изучайте казахский через живой, мотивирующий и измеримый путь.',
    en: 'Learn Kazakh through a living, motivating and trackable journey.',
    kz: 'Қазақ тілін жанды, ынталандыратын және өлшенетін жолмен үйреніңіз.',
  },
  hero_text: {
    ru: 'QazaqApp объединяет уровни, ежедневные задания, speaking-практику, мини-игры, XP, сертификаты и рейтинг в один адаптивный поток.',
    en: 'QazaqApp combines structured levels, daily missions, speaking practice, mini-games, XP, certificates and community ranking into one adaptive learning flow.',
    kz: 'QazaqApp деңгейлерді, күнделікті тапсырмаларды, speaking жаттығуларын, мини-ойындарды, XP, сертификаттар мен рейтингті бір бейімделетін оқу жолына біріктіреді.',
  },
  open_mission_control: { ru: 'Открыть центр прогресса', en: 'Open mission control', kz: 'Прогресс орталығын ашу' },
  continue_levels: { ru: 'Продолжить уровни', en: 'Continue levels', kz: 'Деңгейлерді жалғастыру' },
  create_profile: { ru: 'Создать профиль', en: 'Create profile', kz: 'Профиль ашу' },
  take_diagnostic: { ru: 'Пройти диагностику', en: 'Take diagnostic', kz: 'Диагностикадан өту' },
  rank: { ru: 'Ранг', en: 'Rank', kz: 'Ранг' },
  crown: { ru: 'Корона', en: 'Crown', kz: 'Тәж' },
  streak: { ru: 'Серия', en: 'Streak', kz: 'Серия' },
  days: { ru: 'дней', en: 'days', kz: 'күн' },
  resume: { ru: 'Продолжить', en: 'Resume', kz: 'Жалғастыру' },
  choose_first_module: { ru: 'Выберите первый модуль', en: 'Choose your first module', kz: 'Алғашқы модульді таңдаңыз' },
  stages: { ru: 'Этапы', en: 'Stages', kz: 'Кезеңдер' },
  four_stages: { ru: '4 этапа', en: '4 stages', kz: '4 кезең' },
  modes: { ru: 'Режимы', en: 'Modes', kz: 'Режимдер' },
  video_practice_arcade: { ru: 'Видео + практика + аркада', en: 'Video + practice + arcade', kz: 'Видео + практика + аркада' },
  motivation: { ru: 'Мотивация', en: 'Motivation', kz: 'Мотивация' },
  xp_streaks_badges: { ru: 'XP, серии, бейджи', en: 'XP, streaks, badges', kz: 'XP, серия, бейдждер' },
  quick_start: { ru: 'Быстрый старт', en: 'Quick start', kz: 'Жылдам бастау' },
  browse_learning_path: { ru: 'Открыть учебный путь', en: 'Browse learning path', kz: 'Оқу жолын ашу' },
  resume_lesson: { ru: 'Продолжить урок', en: 'Resume lesson', kz: 'Сабақты жалғастыру' },
  start_first_lesson: { ru: 'Начать первый урок', en: 'Start your first lesson', kz: 'Алғашқы сабақты бастау' },
  complete_short: { ru: 'выполнено', en: 'complete', kz: 'орындалды' },
  active_days: { ru: 'активных дней', en: 'days active', kz: 'белсенді күн' },
  feature_adaptive_title: { ru: 'Адаптивный маршрут', en: 'Adaptive journey', kz: 'Бейімделетін бағыт' },
  feature_adaptive_text: {
    ru: 'Ежедневные задания, 7-дневный челлендж, XP и уровни делают обучение персональным.',
    en: 'Daily tasks, 7-day challenge, XP and level-ups keep the route personal.',
    kz: 'Күнделікті тапсырмалар, 7 күндік челлендж, XP және деңгейлер оқу жолын жекелейді.',
  },
  feature_live_title: { ru: 'Живая практика', en: 'Live practice', kz: 'Тірі практика' },
  feature_live_text: {
    ru: 'Видео, грамматика, shadowing, listening, reading и три формата мини-игр.',
    en: 'Video, grammar, shadowing, listening, reading and three mini-game formats.',
    kz: 'Видео, грамматика, shadowing, listening, reading және үш түрлі мини-ойын.',
  },
  feature_growth_title: { ru: 'Видимый рост', en: 'Visible growth', kz: 'Көрінетін өсу' },
  feature_growth_text: {
    ru: 'Лидерборд, бейджи, сертификаты и аналитика сильных и слабых сторон.',
    en: 'Leaderboard, badges, certificates and strength/weakness analytics.',
    kz: 'Лидерборд, бейдждер, сертификаттар және күшті-әлсіз жақ аналитикасы.',
  },
  word_of_day: { ru: 'Слово дня', en: 'Word of the day', kz: 'Күн сөзі' },
  daily_tradition: { ru: 'Традиция дня', en: 'Tradition of the day', kz: 'Күн дәстүрі' },
  culture_focus: { ru: 'Язык и культура', en: 'Language and culture', kz: 'Тіл және мәдениет' },
  phrase_of_tradition: { ru: 'Фраза традиции', en: 'Phrase of the tradition', kz: 'Дәстүр фразасы' },
  practice_tip: { ru: 'Практика', en: 'Practice', kz: 'Практика' },
  community_pulse: { ru: 'Пульс сообщества', en: 'Community pulse', kz: 'Қауымдастық серпіні' },
  leaderboard_preview: { ru: 'Фрагмент лидерборда', en: 'Leaderboard preview', kz: 'Лидерборд көрінісі' },
  see_all: { ru: 'Смотреть все', en: 'See all', kz: 'Барлығын көру' },
  leaderboard_empty: {
    ru: 'Лидерборд появится, когда ученики начнут набирать очки.',
    en: 'Leaderboard will appear after learners start earning points.',
    kz: 'Оқушылар ұпай жинай бастағанда лидерборд пайда болады.',
  },
  structured_path: { ru: 'Структурный путь', en: 'Structured path', kz: 'Құрылымды жол' },
  level_roadmap: { ru: 'Карта уровней', en: 'Level roadmap', kz: 'Деңгейлер картасы' },
  open_all_levels: { ru: 'Открыть все уровни', en: 'Open all levels', kz: 'Барлық деңгейлерді ашу' },
  auth_identity: { ru: 'Идентичность QazaqApp', en: 'QazaqApp identity', kz: 'QazaqApp болмысы' },
  auth_register_title: { ru: 'Создайте учебный профиль', en: 'Create your learning identity', kz: 'Оқу профилін жасаңыз' },
  auth_login_title: { ru: 'С возвращением', en: 'Welcome back', kz: 'Қайта келдіңіз' },
  auth_register_text: {
    ru: 'Выберите роль, аватар и создайте профиль с сохранением прогресса, XP, рейтинга и сертификатов.',
    en: 'Choose a role, pick an avatar and create a profile with saved progress, leaderboard rank, XP and certificates.',
    kz: 'Рөлді, аватарды таңдап, прогресс, XP, рейтинг және сертификаттар сақталатын профиль жасаңыз.',
  },
  auth_login_text: {
    ru: 'Войдите, чтобы вернуть свою серию, историю обучения, мини-игры, сертификаты и место остановки.',
    en: 'Sign in to recover your streak, mission history, mini-games, certificates and where you stopped.',
    kz: 'Серияны, оқу тарихын, мини-ойындарды, сертификаттарды және тоқтаған жеріңізді қайтару үшін кіріңіз.',
  },
  auth_point_daily: { ru: 'Ежедневные задания и 7-дневный челлендж', en: 'Daily tasks and 7-day challenge', kz: 'Күнделікті тапсырмалар және 7 күндік челлендж' },
  auth_point_word: { ru: 'Слово дня и серии занятий', en: 'Word of the day and study series', kz: 'Күн сөзі және оқу сериялары' },
  auth_point_badges: { ru: 'Бейджи, XP, уровни и лидерборд', en: 'Badges, XP, levels and leaderboard', kz: 'Бейдждер, XP, деңгейлер және лидерборд' },
  name: { ru: 'Имя', en: 'Name', kz: 'Аты' },
  your_name: { ru: 'Ваше имя', en: 'Your name', kz: 'Атыңыз' },
  email_label: { ru: 'Email', en: 'Email', kz: 'Email' },
  password_label: { ru: 'Пароль', en: 'Password', kz: 'Құпиясөз' },
  password_hint: { ru: 'Минимум 6 символов', en: 'At least 6 characters', kz: 'Кемі 6 таңба' },
  role: { ru: 'Роль', en: 'Role', kz: 'Рөл' },
  avatar: { ru: 'Аватар', en: 'Avatar', kz: 'Аватар' },
  role_student: { ru: 'Ученик', en: 'Student', kz: 'Оқушы' },
  role_teacher: { ru: 'Учитель', en: 'Teacher', kz: 'Мұғалім' },
  role_student_desc: {
    ru: 'Личный маршрут обучения с ежедневными задачами, XP и достижениями.',
    en: 'Personal learning path with daily tasks, XP and achievements.',
    kz: 'Күнделікті тапсырмалар, XP және жетістіктері бар жеке оқу жолы.',
  },
  role_teacher_desc: {
    ru: 'Обзор прогресса учеников, задачи и видимость сертификатов.',
    en: 'Progress overview, learners snapshot and certification visibility.',
    kz: 'Оқушылар прогресі, тапсырмалар және сертификаттардың көрінуі.',
  },
  please_wait: { ru: 'Подождите...', en: 'Please wait...', kz: 'Күтіңіз...' },
  already_have_account: { ru: 'Уже есть аккаунт?', en: 'Already have an account?', kz: 'Аккаунтыңыз бар ма?' },
  need_account: { ru: 'Нужен аккаунт?', en: 'Need an account?', kz: 'Аккаунт керек пе?' },
  account_created: { ru: 'Аккаунт создан.', en: 'Account created.', kz: 'Аккаунт құрылды.' },
  signed_in: { ru: 'Вход выполнен.', en: 'Signed in.', kz: 'Кіру орындалды.' },
  request_failed: { ru: 'Не удалось выполнить запрос.', en: 'Unable to complete request.', kz: 'Сұрауды орындау мүмкін болмады.' },
  module_test: { ru: 'Модульный тест', en: 'Module test', kz: 'Модульдік тест' },
  question: { ru: 'Вопрос', en: 'Question', kz: 'Сұрақ' },
  test_complete: { ru: 'Тест завершен', en: 'Test complete', kz: 'Тест аяқталды' },
  score: { ru: 'Результат', en: 'Score', kz: 'Нәтиже' },
  certificate: { ru: 'Сертификат', en: 'Certificate', kz: 'Сертификат' },
  back_to_module: { ru: 'Назад к модулю', en: 'Back to module', kz: 'Модульге оралу' },
  loading_module_test: { ru: 'Загрузка модульного теста...', en: 'Loading module test...', kz: 'Модульдік тест жүктелуде...' },
  loading_diagnostic: { ru: 'Загрузка диагностики...', en: 'Loading diagnostic...', kz: 'Диагностика жүктелуде...' },
  diagnostic_label: { ru: 'Диагностика', en: 'Diagnostic', kz: 'Диагностика' },
  diagnostic_complete: { ru: 'Диагностика завершена', en: 'Diagnostic complete', kz: 'Диагностика аяқталды' },
  correct_answers: { ru: 'Правильных ответов', en: 'Correct answers', kz: 'Дұрыс жауаптар' },
  recommended_level: { ru: 'Рекомендуемый уровень', en: 'Recommended level', kz: 'Ұсынылатын деңгей' },
  open_level: { ru: 'Открыть уровень', en: 'Open level', kz: 'Деңгейді ашу' },
  speech_not_supported: { ru: 'Браузер не поддерживает распознавание речи.', en: 'Speech recognition is not supported in this browser.', kz: 'Бұл браузер сөйлеуді тануды қолдамайды.' },
  answer_required: { ru: 'Сначала ответьте на вопрос.', en: 'Answer the current question first.', kz: 'Алдымен сұраққа жауап беріңіз.' },
  diagnostic_saved: { ru: 'Результат диагностики сохранен.', en: 'Diagnostic result saved.', kz: 'Диагностика нәтижесі сақталды.' },
  diagnostic_save_error: { ru: 'Не удалось сохранить диагностику.', en: 'Unable to save diagnostic result.', kz: 'Диагностика нәтижесін сақтау мүмкін болмады.' },
  module_saved: { ru: 'Модульный тест сохранен.', en: 'Module test saved.', kz: 'Модульдік тест сақталды.' },
  module_save_error: { ru: 'Не удалось сохранить модульный тест.', en: 'Unable to save test result.', kz: 'Модульдік тесті сақтау мүмкін болмады.' },
  pass_badge: { ru: 'СДАНО', en: 'PASS', kz: 'ӨТТІ' },
  retry_badge: { ru: 'ЕЩЁ РАЗ', en: 'TRY AGAIN', kz: 'ҚАЙТА ТАПСЫР' },
  level_studio: { ru: 'Студия уровня', en: 'Level studio', kz: 'Деңгей студиясы' },
  level_completion: { ru: 'Прогресс уровня', en: 'Level completion', kz: 'Деңгей прогресі' },
  current_streak: { ru: 'Текущая серия', en: 'Current streak', kz: 'Ағымдағы серия' },
  open_module: { ru: 'Открыть модуль', en: 'Open module', kz: 'Модульді ашу' },
  today: { ru: 'Сегодня', en: 'Today', kz: 'Бүгін' },
  mission_control: { ru: 'Центр прогресса', en: 'Mission control', kz: 'Прогресс орталығы' },
  milestone: { ru: 'Веха', en: 'Milestone', kz: 'Белес' },
  certificate_status: { ru: 'Статус сертификата', en: 'Certificate status', kz: 'Сертификат күйі' },
  certificate_unlocked: { ru: 'Для этого уровня сертификат уже открыт.', en: 'This level already has an unlocked certificate.', kz: 'Бұл деңгей үшін сертификат ашылған.' },
  view_certificate: { ru: 'Посмотреть сертификат', en: 'View certificate', kz: 'Сертификатты көру' },
  unlock_certificate: { ru: 'Пройдите модульный тест, чтобы открыть сертификат этого уровня.', en: 'Pass the module test to unlock the official certificate for this level.', kz: 'Осы деңгей сертификатын ашу үшін модульдік тесттен өтіңіз.' },
  take_module_test: { ru: 'Пройти модульный тест', en: 'Take module test', kz: 'Модульдік тесттен өту' },
  structured_learning_path: { ru: 'Структурный учебный путь', en: 'Structured learning path', kz: 'Құрылымды оқу жолы' },
  choose_level: { ru: 'Выберите уровень и откройте следующий этап.', en: 'Choose your level and unlock the next stage.', kz: 'Деңгейді таңдап, келесі кезеңді ашыңыз.' },
  levels_intro: { ru: 'Каждый уровень сочетает уроки, практику, мини-игры, недельный ритм и финальную сертификацию.', en: 'Each level combines lessons, practice, mini-games, a weekly rhythm and a final certification milestone.', kz: 'Әр деңгейде сабақтар, практика, мини-ойындар, апталық ырғақ және қорытынды сертификат бар.' },
  run_diagnostic: { ru: 'Запустить диагностику', en: 'Run diagnostic', kz: 'Диагностиканы бастау' },
  current: { ru: 'Текущий', en: 'Current', kz: 'Ағымдағы' },
  recommended: { ru: 'Рекомендуется', en: 'Recommended', kz: 'Ұсынылады' },
  certified: { ru: 'Сертификат есть', en: 'Certified', kz: 'Сертификат бар' },
  completion: { ru: 'Завершение', en: 'Completion', kz: 'Аяқталу' },
  arcade_lab: { ru: 'Аркада', en: 'Arcade Lab', kz: 'Аркада зертханасы' },
  mini_games: { ru: 'мини-игры', en: 'mini-games', kz: 'мини-ойындар' },
  back_to_level: { ru: 'Назад к уровню', en: 'Back to level', kz: 'Деңгейге оралу' },
  loading_arcade: { ru: 'Загрузка аркады...', en: 'Loading arcade...', kz: 'Аркада жүктелуде...' },
  save_result: { ru: 'Сохранить результат', en: 'Save result', kz: 'Нәтижені сақтау' },
  select_translation: { ru: 'Выберите перевод', en: 'Select translation', kz: 'Аударманы таңдаңыз' },
  token_bank: { ru: 'Набор токенов', en: 'Token bank', kz: 'Токендер жиыны' },
  correct_order: { ru: 'Правильный порядок', en: 'Correct order', kz: 'Дұрыс рет' },
  drop: { ru: 'Слот', en: 'Drop', kz: 'Ұяшық' },
  complete_pairs: { ru: 'Заполните все пары перед отправкой.', en: 'Complete every pair before submitting.', kz: 'Жіберер алдында барлық жұпты толтырыңыз.' },
  fill_slots: { ru: 'Заполните все слоты перед отправкой.', en: 'Fill every slot before submitting.', kz: 'Жіберер алдында барлық ұяшықты толтырыңыз.' },
  answer_every_round: { ru: 'Ответьте на каждый раунд перед отправкой.', en: 'Answer every round before submitting.', kz: 'Жіберер алдында әр раундқа жауап беріңіз.' },
  saved_result: { ru: 'Сохранено', en: 'Saved', kz: 'Сақталды' },
  xp_applied: { ru: 'XP начислен в профиль.', en: 'XP reward applied to your profile.', kz: 'XP профильге қосылды.' },
  question_type: { ru: 'Тип задания', en: 'Question type', kz: 'Тапсырма түрі' },
  loading_profile: { ru: 'Загрузка профиля...', en: 'Loading profile...', kz: 'Профиль жүктелуде...' },
  open_learning_path: { ru: 'Открыть учебный путь', en: 'Open learning path', kz: 'Оқу жолын ашу' },
  xp_level: { ru: 'XP уровень', en: 'XP level', kz: 'XP деңгейі' },
  overall_progress: { ru: 'Общий прогресс', en: 'Overall progress', kz: 'Жалпы прогресс' },
  all_content: { ru: 'Все уровни и все типы контента', en: 'All levels and all content types', kz: 'Барлық деңгейлер мен контент түрлері' },
  role_hub: { ru: 'Ролевой центр', en: 'Role hub', kz: 'Рөл орталығы' },
  current_level: { ru: 'Текущий уровень', en: 'Current level', kz: 'Ағымдағы деңгей' },
  consistency: { ru: 'Регулярность', en: 'Consistency', kz: 'Тұрақтылық' },
  study_series: { ru: 'Серии занятий', en: 'Study series', kz: 'Оқу сериясы' },
  acts: { ru: 'действий', en: 'acts', kz: 'әрекет' },
  strong_side: { ru: 'Сильная сторона', en: 'Strong side', kz: 'Күшті жағы' },
  top_skills: { ru: 'Лучшие навыки', en: 'Top skills', kz: 'Үздік дағдылар' },
  growth_zone: { ru: 'Зона роста', en: 'Growth zone', kz: 'Өсу аймағы' },
  weak_skills: { ru: 'Слабые навыки', en: 'Weak skills', kz: 'Әлсіз дағдылар' },
  social_proof: { ru: 'Социальный блок', en: 'Social proof', kz: 'Әлеуметтік блок' },
  full_ranking: { ru: 'Полный рейтинг', en: 'Full ranking', kz: 'Толық рейтинг' },
  milestones: { ru: 'Вехи', en: 'Milestones', kz: 'Белестер' },
  certificates: { ru: 'Сертификаты', en: 'Certificates', kz: 'Сертификаттар' },
  certificates_hint: { ru: 'Сертификаты появляются после прохождения модульного теста.', en: 'Certificates appear after you pass a module test.', kz: 'Сертификаттар модульдік тесттен өткеннен кейін беріледі.' },
  achievement_wall: { ru: 'Стена достижений', en: 'Achievement wall', kz: 'Жетістіктер қабырғасы' },
  badges_and_achievements: { ru: 'Бейджи и достижения', en: 'Badges and achievements', kz: 'Бейдждер мен жетістіктер' },
  teacher_link: { ru: 'Связь с учителем', en: 'Teacher link', kz: 'Мұғаліммен байланыс' },
  teacher_assignment: { ru: 'Назначение учителя', en: 'Teacher assignment', kz: 'Мұғалім тағайындау' },
  weekly_limit: { ru: 'Недельный лимит', en: 'Weekly limit', kz: 'Апталық лимит' },
  used: { ru: 'Использовано', en: 'Used', kz: 'Пайдаланылды' },
  remaining: { ru: 'Осталось', en: 'Remaining', kz: 'Қалды' },
  request_another_teacher: { ru: 'Запросить другого учителя через бота', en: 'Request another teacher via bot', kz: 'Бот арқылы басқа мұғалім сұрау' },
  change_reason: { ru: 'Почему вы хотите сменить?', en: 'Why do you want to change?', kz: 'Неге ауыстырғыңыз келеді?' },
  bot_placeholder: { ru: 'Это сообщение уйдет в Telegram-бот', en: 'This goes to the Telegram bot', kz: 'Бұл хабарлама Telegram ботқа жіберіледі' },
  send_change_request: { ru: 'Отправить запрос', en: 'Send change request', kz: 'Сұрау жіберу' },
  choose_teacher_hint: { ru: 'Каждый студент должен выбрать учителя перед продолжением обучения.', en: 'Each student must select a teacher before continuing the guided learning track.', kz: 'Әр студент бағытталған оқуды жалғастыру алдында мұғалім таңдау керек.' },
  choose_your_teacher: { ru: 'Выберите учителя', en: 'Choose your teacher', kz: 'Өз мұғаліміңізді таңдаңыз' },
  confirm_teacher: { ru: 'Подтвердить учителя', en: 'Confirm teacher', kz: 'Мұғалімді растау' },
  students_count: { ru: 'учеников', en: 'students', kz: 'оқушы' },
  students_will_appear: { ru: 'Ученики появятся здесь после выбора вас как учителя.', en: 'Students will appear here after they choose you as a teacher.', kz: 'Оқушылар сізді мұғалім ретінде таңдаған соң осында көрінеді.' },
  bot_center: { ru: 'Центр бота', en: 'Bot center', kz: 'Бот орталығы' },
  feedback_ideas: { ru: 'Отзыв и идеи по улучшению', en: 'Feedback and improvement ideas', kz: 'Пікір және жақсарту идеялары' },
  unlimited_feedback: { ru: 'Отзывы можно отправлять в Telegram-бот сколько угодно раз.', en: 'Feedback messages can be sent to the Telegram bot as many times as needed.', kz: 'Пікірлерді Telegram ботқа шексіз жібере аласыз.' },
  your_feedback: { ru: 'Ваш отзыв', en: 'Your feedback', kz: 'Сіздің пікіріңіз' },
  improve_placeholder: { ru: 'Что можно улучшить?', en: 'What should be improved?', kz: 'Нені жақсартуға болады?' },
  send_feedback: { ru: 'Отправить отзыв', en: 'Send feedback', kz: 'Пікір жіберу' },
  assignments: { ru: 'Задания', en: 'Assignments', kz: 'Тапсырмалар' },
  create_tasks_for_students: { ru: 'Создать задания для учеников', en: 'Create tasks for students', kz: 'Оқушыларға тапсырма құру' },
  tasks_from_teacher: { ru: 'Задания от учителя', en: 'Tasks from your teacher', kz: 'Мұғалім тапсырмалары' },
  student: { ru: 'Ученик', en: 'Student', kz: 'Оқушы' },
  task_title: { ru: 'Название задания', en: 'Task title', kz: 'Тапсырма атауы' },
  description: { ru: 'Описание', en: 'Description', kz: 'Сипаттама' },
  due_date: { ru: 'Срок', en: 'Due date', kz: 'Мерзімі' },
  no_due_date: { ru: 'Без срока', en: 'No due date', kz: 'Мерзімі жоқ' },
  open_status: { ru: 'Открыто', en: 'Open', kz: 'Ашық' },
  completed_status: { ru: 'Выполнено', en: 'Completed', kz: 'Орындалды' },
  no_teacher_tasks: { ru: 'Пока нет заданий от учителя.', en: 'No teacher tasks yet.', kz: 'Әзірге мұғалім тапсырмалары жоқ.' },
  student_tasks_appear: { ru: 'Задания учителя появятся здесь.', en: 'Your teacher tasks will appear here.', kz: 'Мұғалім тапсырмалары осында көрінеді.' },
  private_hub: { ru: 'Приватный центр', en: 'Private hub', kz: 'Жеке орталық' },
  sign_in_profile: { ru: 'Войдите, чтобы открыть центр прогресса', en: 'Sign in to unlock your mission control', kz: 'Прогресс орталығын ашу үшін кіріңіз' },
  profile_login_hint: { ru: 'После входа появятся ежедневные задания, серия, рейтинг и сертификаты.', en: 'Your daily tasks, streak rewards, leaderboard rank and certificates appear after login.', kz: 'Кіргеннен кейін күнделікті тапсырмалар, серия, рейтинг және сертификаттар көрінеді.' },
  open_login: { ru: 'Открыть вход', en: 'Open login', kz: 'Кіруді ашу' },
  certificate_title: { ru: 'Языковой сертификат QazaqApp', en: 'QazaqApp Language Certificate', kz: 'QazaqApp тіл сертификаты' },
  verified_certificate: { ru: 'Подтвержденный сертификат', en: 'Verified certificate', kz: 'Расталған сертификат' },
  awarded_for_level: { ru: 'Выдан за успешное завершение уровня', en: 'Awarded for successful completion of level', kz: 'Деңгейді сәтті аяқтағаны үшін берілді' },
  presented_to: { ru: 'Вручается', en: 'Presented to', kz: 'Тапсырылады' },
  issued: { ru: 'Выдан', en: 'Issued', kz: 'Берілген күні' },
  certificate_statement: { ru: 'Этот сертификат подтверждает, что ученик завершил модуль, прошел финальную оценку и открыл официальный milestone в QazaqApp.', en: 'This certificate confirms that the learner completed the full module, passed the final assessment and unlocked the official milestone inside the QazaqApp learning path.', kz: 'Бұл сертификат оқушының модульді аяқтап, қорытынды бағалаудан өтіп, QazaqApp ішіндегі ресми белесті ашқанын растайды.' },
  print_save_pdf: { ru: 'Печать / PDF', en: 'Print / Save PDF', kz: 'Басып шығару / PDF' },
  back_to_profile: { ru: 'Назад в профиль', en: 'Back to profile', kz: 'Профильге оралу' },
  certificate_locked: { ru: 'Сертификат заблокирован', en: 'Certificate locked', kz: 'Сертификат бұғатталған' },
  certificate_not_unlocked: { ru: 'Сертификат этого уровня еще не открыт', en: 'Certificate not unlocked yet', kz: 'Бұл деңгей сертификаты әлі ашылған жоқ' },
  pass_module_for_certificate: { ru: 'Пройдите модульный тест этого уровня, чтобы получить сертификат.', en: 'Pass the module test for this level to generate the certificate.', kz: 'Сертификат алу үшін осы деңгейдің модульдік тестінен өтіңіз.' },
  go_to_levels: { ru: 'К уровням', en: 'Go to levels', kz: 'Деңгейлерге өту' },
  profile_required: { ru: 'Нужен профиль', en: 'Profile required', kz: 'Профиль қажет' },
  sign_in_certificates: { ru: 'Войдите, чтобы видеть сертификаты', en: 'Sign in to view certificates', kz: 'Сертификаттарды көру үшін кіріңіз' },
  certificates_tied: { ru: 'Сертификаты связаны с прогрессом вашего аккаунта и завершенными тестами.', en: 'Your certificates are tied to your account progress and completed module tests.', kz: 'Сертификаттар аккаунт прогресімен және аяқталған тесттермен байланысқан.' },
  loading_certificate: { ru: 'Загрузка сертификата...', en: 'Loading certificate...', kz: 'Сертификат жүктелуде...' },
  video_lessons: { ru: 'Видеоуроки', en: 'Video lessons', kz: 'Видео сабақтар' },
  grammar_lab: { ru: 'Грамматика', en: 'Grammar lab', kz: 'Грамматика' },
  shadowing: { ru: 'Shadowing', en: 'Shadowing', kz: 'Shadowing' },
  four_skills: { ru: 'Четыре навыка', en: 'Four skills', kz: 'Төрт дағды' },
  arcade_zone: { ru: 'Аркада', en: 'Arcade zone', kz: 'Аркада аймағы' },
  final_checkpoint: { ru: 'Финальный рубеж', en: 'Final checkpoint', kz: 'Қорытынды белес' },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private readonly platformId = inject(PLATFORM_ID);
  readonly lang = signal<AppLanguage>('ru');

  constructor() {
    if (isPlatformBrowser(this.platformId)) {
      const stored = window.localStorage.getItem(storageKey) as AppLanguage | null;
      if (stored === 'ru' || stored === 'en' || stored === 'kz') {
        this.lang.set(stored);
      }
    }
  }

  setLanguage(next: AppLanguage): void {
    this.lang.set(next);
    if (isPlatformBrowser(this.platformId)) {
      window.localStorage.setItem(storageKey, next);
    }
  }

  t(key: string): string {
    return dictionary[key]?.[this.lang()] ?? key;
  }

  text(value: string | LocalizedText | undefined | null): string {
    if (!value) {
      return '';
    }
    if (typeof value === 'string') {
      return value;
    }
    return value[this.lang()];
  }
}
